### ISSUE TITLE
Activate travis builds

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-lightning-invoice#1]
It would be nice if someone with sufficient rights could activate travis builds for this repository. I assume that would be @TheBlueMatt as org owner? Thanks in advance :)

**Comment by TheBlueMatt** [comment]
For some reason when you transfer a repo it resets so that you are only write...I set you to admin since its your repo, I think that should be sufficient to turn travis on.

**Comment by TheBlueMatt** [comment]
That said, I wenat ahead and did it, it should be running.

**Comment by sgeisler** [comment]
Thank you, after resyncing my account I could edit the repo's settings.
