### ISSUE TITLE
[FR] Getter for fallbacks as Address'es

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-lightning-invoice#24]
The `fallback()` method returns some custom address payload implementation. A regular `fallback_addresses` or so that is just a `Vec<Address>` would be great.

**Comment by stevenroose** [comment]
Or an `Into<Address>` for `Fallback`.

**Comment by sgeisler** [comment]
Migrated to rust-bitcoin/rust-lightning#882
