### ISSUE TITLE
Return non-wrapped types from `Invoice` getters if possible

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-lightning-invoice#26]
The `Invoice` type has the highest level of abstraction in `rust-lightning-invoice` and aims to provide an ergonomic API. @stetvenroose pointed out in #23 that the internal newtypes are rather inconvenient and I agree, but unfortunately we can't get rid of them.

I'd propose to at least make the `Invoice` interface as conevnient as possible by making the getters return the inner type of the respective newtype:

* `payment_hash` should return `bitcoin_hashes::sha256::Hash` instead of `Sha256`
* `payee_pub_key` and `recover_payee_pub_key` should return `secp256k1::...::PublicKey` instead of `PayeePubKey`
* `expiry_time` should return `std::time::Duration` instead of `ExpiryTime`
* `min_final_cltv_expiry` should return `u64` instead of `MinFinalCltvExpiry`

@TheBlueMatt and @stevenroose do you think that's an improvement?

**Comment by stevenroose** [comment]
Copied from https://github.com/rust-bitcoin/rust-lightning-invoice/issues/23:
> Yeah the code of this crate very much confuses me. The whole idea of keeping the fields around and so might have overcomplicated it.
> 
> Don't you think it'd be able to take an approach like @dongcarl's PSBT implementation where you just assign all fields during deserialization?

I don't know why the current design was built like it is, but reading the BOLT 11 spec, it seems to be quite similar to the PSBT format serialization.
