### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning-invoice#4]
It seems like the num-traits and regex deps could easily be removed, which would be nice to reduce root-of-trust, especially given regex's rather large deps (and to reduce footprint, maybe even making nostd possible for invoice parsing).

**Comment by sgeisler** [comment]
I agree for `regex`, it just wasn't high on my priority list since it should be rather easy to do before the first release.

`num-traits` is useful for generic base conversion, but it would probably be ok to always convert to and from `u64`'s and do the necessary conversions.

**Comment by sgeisler** [comment]
The `regex` dependency was removed in dafaf48 and replaced by a custom state machine. But I will probably reintroduce it as dev dependency to test the state machine.

**Comment by TheBlueMatt** [comment]
Awesome, thanks!
