### ISSUE TITLE
Need an easy way to get unsigned part from a RawInvoice

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning-invoice#6]
The first thing you want to do with an invoice is check the sig and recover the pubkey for the destination, but there is no simple way to do that.

**Comment by TheBlueMatt** [comment]
This is also important for being able to *create* invoices.

**Comment by sgeisler** [comment]
I removed the signature from the raw invoice. There is one more data structure now (`RawSignedInvoice`) which contains a `RawInvoice`, its hash and a signature. One can sign a `RawInvoice` by supplying a function that signs a `Message` (the hash).

**Comment by TheBlueMatt** [comment]
New API works for me, thanks!
