### ISSUE TITLE
Replace bitcoin_hashes with crates.io version

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-lightning-invoice#9]
@apoelstra needs to publish rust-bitcoin/bitcoin_hashes first (at least I think you were the one maintaining it).

**Comment by apoelstra** [comment]
Yes, it's me. I need all the open PRs to be merged first (or maybe I should just force them through at this point).

**Comment by sgeisler** [comment]
I don't think we should skip review because of that. How bad would it be to just release a `0.1.0` without the PRs and a `0.2.0`/`0.1.1` after they got merged? If I understand it correctly these PRs are waiting for review, if you want I can have a look at them later or try to get @dongcarl to review them with me.

**Comment by dongcarl** [comment]
@sgeisler and I will review on Tuesday.
